[package]

name = "zip"
version = "0.3.0"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
license = "MIT"
repository = "https://github.com/mvdnes/zip-rs.git"
documentation = "http://mvdnes.github.io/rust-docs/zip-rs/zip/index.html"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""

[dependencies]
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"], optional = true}
podio = "0.1"
bzip2 = { version = "0.3", optional = true }

[dev-dependencies]
walkdir = "1.0"

[features]
deflate = ["flate2"]
default = ["deflate"]

[patch.crates-io]
miniz_oxide = {  path = "../miniz_oxide/miniz_oxide" }
miniz_oxide_c_api = { path = "../miniz_oxide" }
flate2 = { path = "../flate2-rs" }
